### ISSUE TITLE
NPC Placement

### ISSUE THREAD

**Issue by creightonjoiner** [QuasiStellar/Re-Remixed_Dungeon#1]
In the village there is a small chance that an NPC spawns on the staircase to get down into the dungeon. 
![Screenshot_20191212-154859](https://user-images.githubusercontent.com/35327497/70744390-f8822500-1cf7-11ea-9b0a-e65a591d7998.png)

**Comment by QuasiStellar** [comment]
Actually I intentionally kept it, so players can laugh at pacifistic villagers and restart the run. Is it really an issue?

**Comment by creightonjoiner** [comment]
Ah no, it isn't really a problem, I just thought it was an over looked bug. My bad! (I too get a kick out of it to be fair)
